import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface ParsedElement {
  type: "h1" | "h2" | "h3" | "paragraph" | "bullet" | "table" | "bold_paragraph";
  content: string;
  rows?: string[][];
  headers?: string[];
}

function stripMarkdown(text: string): string {
  return text
    .replace(/\*\*([^*]+)\*\*/g, "$1")   // **bold**
    .replace(/\*([^*]+)\*/g, "$1")        // *italic*
    .replace(/_([^_]+)_/g, "$1")          // _italic_
    .replace(/`([^`]+)`/g, "$1")          // `code`
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1") // [link](url)
    .replace(/~~([^~]+)~~/g, "$1")        // ~~strikethrough~~
    .trim();
}

function parseMarkdownToElements(markdown: string): ParsedElement[] {
  const lines = markdown.split("\n");
  const elements: ParsedElement[] = [];
  let i = 0;

  while (i < lines.length) {
    const line = lines[i].trim();

    if (!line) {
      i++;
      continue;
    }

    // Headings
    if (line.startsWith("### ")) {
      elements.push({ type: "h3", content: line.replace(/^###\s+/, "") });
      i++;
      continue;
    }
    if (line.startsWith("## ")) {
      elements.push({ type: "h2", content: line.replace(/^##\s+/, "") });
      i++;
      continue;
    }
    if (line.startsWith("# ")) {
      elements.push({ type: "h1", content: line.replace(/^#\s+/, "") });
      i++;
      continue;
    }

    // Table detection — handles both `| col | col |` and `col | col` formats
    if (line.includes("|") && i + 1 < lines.length && lines[i + 1].trim().match(/^[\s\-:|]+$/)) {
      const headerCells = line.split("|").map((c) => stripMarkdown(c)).filter(Boolean);
      i += 2;
      const rows: string[][] = [];
      while (i < lines.length && lines[i].trim().includes("|")) {
        const trimmed = lines[i].trim();
        if (!trimmed || trimmed.match(/^[\s\-:|]+$/)) { i++; continue; }
        const row = trimmed.split("|").map((c) => stripMarkdown(c)).filter(Boolean);
        if (row.length > 0) rows.push(row);
        i++;
      }
      elements.push({ type: "table", content: "", headers: headerCells, rows });
      continue;
    }

    // Bullet points
    if (line.match(/^[-*]\s+/) || line.match(/^\d+\.\s+/)) {
      const content = line.replace(/^[-*]\s+/, "").replace(/^\d+\.\s+/, "");
      elements.push({ type: "bullet", content });
      i++;
      continue;
    }

    // Bold paragraph (starts with **)
    if (line.startsWith("**")) {
      elements.push({ type: "bold_paragraph", content: line });
      i++;
      continue;
    }

    // Regular paragraph
    elements.push({ type: "paragraph", content: line });
    i++;
  }

  return elements;
}

export function generatePolicyPDF(
  markdown: string,
  title: string,
  companyName?: string
): jsPDF {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  const company = companyName || "[COMPANY NAME]";

  // ── COVER PAGE ──
  doc.setFillColor(11, 10, 26);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  doc.setTextColor(129, 140, 248);
  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text(company.toUpperCase(), pageWidth / 2, 60, { align: "center" });

  doc.setTextColor(226, 224, 240);
  doc.setFontSize(26);
  doc.setFont("helvetica", "bold");
  const titleLines = doc.splitTextToSize(stripMarkdown(title), contentWidth);
  doc.text(titleLines, pageWidth / 2, 90, { align: "center" });

  const dividerY = 90 + titleLines.length * 12 + 15;
  doc.setDrawColor(129, 140, 248);
  doc.setLineWidth(0.5);
  doc.line(pageWidth / 2 - 30, dividerY, pageWidth / 2 + 30, dividerY);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(160, 156, 192);
  doc.text("Version 1.0", pageWidth / 2, dividerY + 15, { align: "center" });
  doc.text("Effective Date: [TO BE DETERMINED]", pageWidth / 2, dividerY + 23, { align: "center" });
  doc.text("Status: Draft", pageWidth / 2, dividerY + 31, { align: "center" });

  doc.setFontSize(9);
  doc.setTextColor(139, 135, 184);
  doc.text("Generated by Complyze — complyze.dev", pageWidth / 2, pageHeight - 25, { align: "center" });
  doc.text(`Confidential — ${company}`, pageWidth / 2, pageHeight - 18, { align: "center" });

  // ── TABLE OF CONTENTS ──
  doc.addPage();
  let y = margin;

  const addHeaderFooter = () => {
    const pn = doc.getNumberOfPages();
    doc.setFontSize(8);
    doc.setTextColor(139, 135, 184);
    doc.text(`Confidential — ${company}`, margin, 10);
    doc.text(`Page ${pn}`, pageWidth - margin, pageHeight - 10, { align: "right" });
  };

  addHeaderFooter();

  doc.setTextColor(40, 40, 40);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Table of Contents", margin, y + 5);
  y += 15;

  const elements = parseMarkdownToElements(markdown);
  const tocEntries = elements.filter((e) => e.type === "h1" || e.type === "h2" || e.type === "h3");
  doc.setFont("helvetica", "normal");

  for (const entry of tocEntries) {
    const indent = entry.type === "h1" ? 0 : entry.type === "h2" ? 6 : 12;
    const fontSize = entry.type === "h1" ? 11 : entry.type === "h2" ? 10 : 9;
    doc.setFontSize(fontSize);
    if (entry.type === "h1") doc.setFont("helvetica", "bold");
    else doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);
    doc.text(stripMarkdown(entry.content), margin + indent, y);
    y += entry.type === "h1" ? 8 : 6;
    if (y > pageHeight - 30) {
      doc.addPage();
      addHeaderFooter();
      y = margin;
    }
  }

  // ── BODY ──
  doc.addPage();
  addHeaderFooter();
  y = margin;

  const checkPageBreak = (needed: number) => {
    if (y + needed > pageHeight - 20) {
      doc.addPage();
      addHeaderFooter();
      y = margin;
    }
  };

  for (const el of elements) {
    switch (el.type) {
      case "h1":
        checkPageBreak(20);
        doc.setFontSize(18);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(30, 30, 30);
        y += 6;
        doc.text(stripMarkdown(el.content), margin, y);
        y += 10;
        break;

      case "h2":
        checkPageBreak(16);
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(50, 50, 50);
        y += 5;
        doc.text(stripMarkdown(el.content), margin, y);
        y += 8;
        break;

      case "h3":
        checkPageBreak(12);
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(60, 60, 60);
        y += 3;
        doc.text(stripMarkdown(el.content), margin, y);
        y += 7;
        break;

      case "paragraph":
      case "bold_paragraph": {
        const text = stripMarkdown(el.content);
        doc.setFontSize(10);
        doc.setFont("times", el.type === "bold_paragraph" ? "bold" : "normal");
        doc.setTextColor(40, 40, 40);
        const wrapped = doc.splitTextToSize(text, contentWidth);
        checkPageBreak(wrapped.length * 5 + 2);
        doc.text(wrapped, margin, y);
        y += wrapped.length * 5 + 3;
        break;
      }

      case "bullet": {
        const bulletText = stripMarkdown(el.content);
        doc.setFontSize(10);
        doc.setFont("times", "normal");
        doc.setTextColor(40, 40, 40);
        const bulletWrapped = doc.splitTextToSize(bulletText, contentWidth - 8);
        checkPageBreak(bulletWrapped.length * 5 + 2);
        doc.text("\u2022", margin + 2, y);
        doc.text(bulletWrapped, margin + 8, y);
        y += bulletWrapped.length * 5 + 2;
        break;
      }

      case "table":
        if (el.headers && el.rows) {
          checkPageBreak(20);
          autoTable(doc, {
            startY: y,
            head: [el.headers],
            body: el.rows,
            margin: { left: margin, right: margin },
            styles: {
              fontSize: 8,
              cellPadding: 2.5,
              textColor: [40, 40, 40],
              lineColor: [200, 200, 200],
              lineWidth: 0.25,
              font: "helvetica",
            },
            headStyles: {
              fillColor: [99, 102, 241],
              textColor: [255, 255, 255],
              fontStyle: "bold",
              fontSize: 8,
            },
            alternateRowStyles: {
              fillColor: [245, 245, 255],
            },
            didDrawPage: () => {
              addHeaderFooter();
            },
          });
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          y = (doc as any).lastAutoTable?.finalY + 6 || y + 20;
        }
        break;
    }
  }

  return doc;
}
