"use client";

import { useState } from "react";
import { Download, FileJson, FileText, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { AuditReport } from "@/lib/types/audit";

interface ExportButtonsProps {
  report: AuditReport;
}

export function ExportButtons({ report }: ExportButtonsProps) {
  const [exporting, setExporting] = useState(false);

  function exportJSON() {
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `complyze-audit-${new Date().toISOString().split("T")[0]}.json`;
    a.click();
    URL.revokeObjectURL(url);
  }

  async function exportPDF() {
    setExporting(true);
    try {
      const { default: jsPDF } = await import("jspdf");
      const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

      const pageW = doc.internal.pageSize.getWidth();
      let y = 20;

      // Header
      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      doc.text("Complyze Compliance Audit Report", 20, y);
      y += 8;
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(120);
      doc.text(`Generated: ${new Date().toLocaleString()} | complyze.dev`, 20, y);
      y += 6;

      // Line
      doc.setDrawColor(200);
      doc.line(20, y, pageW - 20, y);
      y += 8;

      // Summary
      doc.setTextColor(0);
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text("Summary", 20, y);
      y += 7;
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(`Risk Score: ${report.overall_risk_score}/100 (${report.risk_level.toUpperCase()})`, 20, y);
      y += 5;
      doc.text(`Findings: ${report.findings.length} | Jurisdictions: ${report.jurisdiction_results.length} | Regulations Checked: ${report.regulations_checked}`, 20, y);
      y += 10;

      // Findings by jurisdiction
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text("Findings", 20, y);
      y += 7;

      for (const finding of report.findings) {
        if (y > 270) {
          doc.addPage();
          y = 20;
        }

        doc.setFontSize(9);
        doc.setFont("helvetica", "bold");
        const severityTag = `[${finding.severity.toUpperCase()}]`;
        doc.text(`${severityTag} ${finding.title}`, 20, y);
        y += 4.5;
        doc.setFont("helvetica", "normal");
        doc.setTextColor(80);

        const descLines = doc.splitTextToSize(finding.description, pageW - 44);
        doc.text(descLines, 24, y);
        y += descLines.length * 4 + 1;

        if (finding.regulation_title) {
          doc.text(`Regulation: ${finding.regulation_title}`, 24, y);
          y += 4;
        }
        if (finding.remediation) {
          const remLines = doc.splitTextToSize(`Remediation: ${finding.remediation}`, pageW - 44);
          doc.text(remLines, 24, y);
          y += remLines.length * 4;
        }

        doc.setTextColor(0);
        y += 4;
      }

      // Recommendations
      if (report.recommendations.length > 0) {
        if (y > 250) { doc.addPage(); y = 20; }
        y += 4;
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text("Recommendations", 20, y);
        y += 7;
        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        for (let i = 0; i < report.recommendations.length; i++) {
          if (y > 270) { doc.addPage(); y = 20; }
          const lines = doc.splitTextToSize(`${i + 1}. ${report.recommendations[i]}`, pageW - 44);
          doc.text(lines, 24, y);
          y += lines.length * 4 + 2;
        }
      }

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text("Generated by Complyze — complyze.dev", 20, doc.internal.pageSize.getHeight() - 10);

      doc.save(`complyze-audit-${new Date().toISOString().split("T")[0]}.pdf`);
    } catch (err) {
      console.error("PDF export failed:", err);
    } finally {
      setExporting(false);
    }
  }

  return (
    <div className="flex gap-2">
      <Button variant="outline" size="sm" onClick={exportJSON} className="text-xs font-mono">
        <FileJson className="h-3.5 w-3.5 mr-1.5" />
        JSON
      </Button>
      <Button variant="outline" size="sm" onClick={exportPDF} disabled={exporting} className="text-xs font-mono">
        {exporting ? (
          <Loader2 className="h-3.5 w-3.5 mr-1.5 animate-spin" />
        ) : (
          <FileText className="h-3.5 w-3.5 mr-1.5" />
        )}
        PDF
      </Button>
    </div>
  );
}
